### ISSUE TITLE
Sample sample_sendreceive_test.go is missing

### ISSUE THREAD

**Issue by brinm00** [ibm-messaging/mq-golang-jms20#17]
README.md points to a non-existing source file: both in the URL's as in the descriptive text.

**Comment by matrober-uk** [comment]
Hi @brinm00 - thanks for raising this issue - it looks like I accidentally renamed that testcase file rather than copying it when I was building the local transaction testcases a while back.

I've restored the original file which has fixed the links you highlighted in the readme (and also made the testcase visible to be executed again!).

Please can you close this issue once you've been able to verify that has resolved the issue?
Regards, Matt.

**Comment by brinm00** [comment]
Thanks Matt, works OK now.

Kind regards,
Melis
