### ISSUE TITLE
Golang send messages to IBM MQ Error MQRC_CONNECTION_BROKEN

### ISSUE THREAD

**Issue by panyaxbo** [ibm-messaging/mq-golang-jms20#31]
Hi,

I'm now working with Golang to connect IBM Websphere MQ-ESB.
Generally, it can send the messages to MQ-ESB , but when something wrong happen the error MQ Connection Broken. This cause my app could not any longer send the messages to the MQ-ESB. Restarting service is the way to solve this issue (but it is not the way solve). 

Anyone has ideas? 

Thanks

**Comment by matrober-uk** [comment]
Hi @panyaxbo - the best approach is to ensure that your application is coded defensively to detect errors like connection broken and to recreate the connection in order to recover - there are some examples of the pattern for error handling in [sample_errorhandling_test.go](https://github.com/ibm-messaging/mq-golang-jms20/blob/master/sample_errorhandling_test.go) that show how to detect the error.  That approach also enables your application to understand where it was at the point that the error took place so that it can take any corrective action if necessary.

The underlying MQ client also has an "auto reconnect" setting [MQCNO_RECONNECT](https://github.com/ibm-messaging/mq-golang/blob/bef14c7b0cd2687257b4a4bdec2d8c36e73d030d/ibmmq/cmqc_linux_amd64.go#L1279) that can transparently recover from certain types of failure on behalf of your application, but that option isn't currently exposed through this JMS style library - it's one of the candidate [next features](https://github.com/ibm-messaging/mq-golang-jms20/blob/master/next-features.txt) if you or others would like to contribute.

Regards,

Matt

**Comment by matrober-uk** [comment]
Closing as answered/old, thanks!
