### ISSUE TITLE
error while loading shared libraries: mqm.dll

### ISSUE THREAD

**Issue by ramkumarar** [ibm-messaging/mq-golang-jms20#34]
Getting the error "error while loading shared libraries: mqm.dll: cannot open shared object file: No such file or directory" when trying to run the program which includes this library in windows, The code is compiling successfully but when i run the code i get this error, Any pointers would be helpful

I can see this dll in ${MQ_Client_Insall_Path}/9.1.5.0-IBM-MQC-Redist-Win64/bin/mqm.dll, 
I tried to set the environment variable LD_LIBRARY_PATH pointing to the above path but still get the error

**Comment by matrober-uk** [comment]
Hi @ramkumarar - I would recommended walking through the [specific instructions for Windows](https://github.com/ibm-messaging/mq-golang#windows) in the mq-golang package instructions (on which this package is based), including insuring that you have the correct Windows-style slash direction between directory path segments -for example in your description above you have Linux style forward-slashes "/" rather than Windows style back-slash "\".

If you're still having problems after that please can you post a full description of your environment including the directory layout and environment variables/commands you run.

**Comment by ramkumarar** [comment]
MQ client installed in path : c:\dev\IBM-MQC-Redist-Win64

Then i set the following environment varaiables

set CC=C:\dev\tools\gcc\bin\x86_64-w64-mingw32-gcc.exe
set CGO_CFLAGS=-Ic:\dev\IBM-MQC-Redist-Win64\tools\c\include -D_WIN64
set CGO_LDFLAGS=-L c:\dev\IBM-MQC-Redist-Win64\bin64 -lmqm

GO env output as below
λ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\XXX\AppData\Local\go-build
set GOENV=C:\Users\XXX\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\dev\work\work-go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\dev\work\work-go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\dev\tools\go-1.15\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\dev\tools\go-1.15\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=C:\dev\tools\gcc\bin\x86_64-w64-mingw32-gcc.exe
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\dev\work\work-poc\golang\mqctl\go.mod
set CGO_CFLAGS=-Ic:\dev\IBM-MQC-Redist-Win64\tools\c\include -D_WIN64
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-L c:\dev\IBM-MQC-Redist-Win64\bin64 -lmqm
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\XXX\AppData\Local\Temp\go-build181335362=/tmp/go-build -gno-record-gcc-switches

In the code i have just the ConnectionFactory creation,
cf := mqjms.ConnectionFactoryImpl{
		QMName:      "Queue Manager",
		Hostname:    "My Broker Host",
		PortNumber:   MY BrokerPort,
		ChannelName: "My Channel",
		UserName:    "",
		Password:    "",
	}
	
my go.mod contains following entries	

module xyz.com/app/mqctl	
go 1.15

require github.com/ibm-messaging/mq-golang-jms20 v1.3.0


The program is compiling successfully and producing executable. When i run in windows terminal it gives blank output, When i run with bash terminal i get the error C:/dev/work/work-poc/golang/mqctl/main.exe: error while loading shared libraries: mqm.dll: cannot open shared object file: No such file or direct

**Comment by matrober-uk** [comment]
Hi @ramkumarar - thanks for the details you shared.

The first sentence of your final paragraph suggests that everything is working correctly in native Windows - which is good, as the code snippet you shared is not expected to create any output to the terminal window. 
> The program is compiling successfully and producing executable. When i run in windows terminal it gives blank output

So to your second comment;
> When i run with bash terminal i get the error

Can you describe the approach you're taking to run Bash on your Windows machine please?  For example are you using Cygwin, or are you running something like Ubuntu via the Windows Subsystem for Linux?

I don't have much personal experience on Windows, but my initial suggestions are;
- Cygwin
  - Might need the environment variables inside the Bash terminal to use Linux style slashes rather than Windows, since the terminal environment is pretending to be Linux?
- Ubuntu/similar via WSL
  - My understanding is this is intended to be "real Linux" so you probably need to compile the binary from inside the Linux terminal, as if it were a real Linux machine?

**Comment by ramkumarar** [comment]
@matrober-uk  It seems the problem is with the run time dependency. I have to add the following location to windows path variable " C:\dev\IBM-MQC-Redist-Win64\bin64", Once i added it I no longer see the error "cannot open shared object file: No such file or direct"
