### ISSUE TITLE
MQRC_SSL_INITIALIZATION_ERROR 

### ISSUE THREAD

**Issue by ramkumarar** [ibm-messaging/mq-golang-jms20#36]
Having issues with mtls connection working

//Java MQ Connection establishment
MQQueueConnectionFactory factory = new MQQueueConnectionFactory();
factory.setSSLSocketFactory(sslContext.getSocketFactory());

factory.setTransportType(JMSC.MQJMS_TP_CLIENT_MQ_TCPIP); //1
factory.setQueueManager(QMGRNAME);
factory.setConnectionNameList(connectionName); // host and port
factory.setChannel(CHANNEL);
factory.setSSLCipherSuite("TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384");

QueueConnection connection = null;
connection = factory.createQueueConnection("",""); //empty user, pass to avoid MQJMS2013 messages
connection.start();

// Tried to do the same with Golang

cf, cfErr := mqjms.CreateConnectionFactoryFromDefaultJSONFiles() //queueManagerName, host,port and channel name are defined here 
if cfErr != nil {		
	return
}	

cf.TLSCipherSpec = "ECDHE_RSA_WITH_AES_256_GCM_SHA384" // I tried with ANY_TLS12 still get the same SSL initialization error
cf.TLSClientAuth = mqjms.TLSClientAuth_REQUIRED
cf.CertificateLabel = "" // took certificate alias from jks, may be the problem is here
cf.KeyRepository = "./certs/key"              // converted jks to kdb and have key.kdb,key.rdb and key.sth under ./certs
context, errCtx := cf.CreateContext()        // Getting error while creating context 

{errorCode=2393, reason=MQRC_SSL_INITIALIZATION_ERROR, linkedErr=MQCONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_SSL_INITIALIZATION_ERROR [2393]}	

Can you let me know what i may be doing wrong here, The java version works fine but get error with golang code

**Comment by matrober-uk** [comment]
Hi @ramkumarar - a few suggestions here to help with the debugging;

- The certificate label being empty string "" in your Golang code snippet looks suspicious to me - it should normally be a non-empty string that is the label from the keystore (unless you had just removed the value from your example)
- If you look at the queue manager error log (e.g. AMQERR01.LOG on the queue manager machine) then it is likely to give some additional details on what the cause of the problem is
  - that will probably say "no client certificate provided" or something similar, which would confirm that a client cert is not presented (due to the label not being present)
  - alternatively it might describe some other error, like a mismatch in CipherSpec (although that's less likely if the same cipher suite worked in your Java case)
- As a fallback there is a worked example in the [tls-samples readme](https://github.com/ibm-messaging/mq-golang-jms20/tree/master/tls-samples) and code examples in [tls_connections_test.go](https://github.com/ibm-messaging/mq-golang-jms20/blob/master/tls_connections_test.go)

hope that helps!

**Comment by ramkumarar** [comment]
@matrober-uk  The issue is resolved, Thanks for the pointers, Had to change the cipher spec to "ECDHE_RSA_AES_256_GCM_SHA384" where as with java code i was using "ECDHE_RSA_WITH_AES_256_GCM_SHA384",
