### ISSUE TITLE
"WithMaxMsgLength" Option not working

### ISSUE THREAD

**Issue by ChipArtem** [ibm-messaging/mq-golang-jms20#60]
9.3.1.0-IBM-MQ-DevToolkit-MacOS
github.com/ibm-messaging/mq-golang-jms20 v1.9.0

I'm trying to read a 100kb message, but I'm getting error MQRC_TRUNCATED_MSG_FAILED [2080]}
After reading the description, I set option: jms20subset.WithMaxMsgLength(153600)

But the error still persists, what am I doing wrong? Or it`s bug?
```

connF := mqjms.ConnectionFactoryImpl{...}

opt :=  jms20subset.WithMaxMsgLength(153600)

context, err := connF.CreateContext(opt)
  if e != nil {
        ....
    }

rQ := context.CreateQueue("Q_OUT")

consumer, err := context.CreateConsumer(qOut)
  if err != nil {
  ....
  }
msg, err := consumer.ReceiveBytesBodyNoWait()
  if err != nil {
  log.Printf("ReceiveBytesBodyNoWait: %v", err)
  }
  
  ERRO[0001] GoError: ReceiveBytesBodyNoWait: {errorCode=2080, reason=MQRC_TRUNCATED_MSG_FAILED, linkedErr=MQGET: MQCC = MQCC_WARNING [1] MQRC = MQRC_TRUNCATED_MSG_FAILED [2080]}
```

**Comment by matrober-uk** [comment]
Hi @ChipArtem, looking at the code snippet you shared I think the issue is that the MaxLength is not being set in the expected way (e.g. line 2).

There are examples how to increase the maximum length setting the attribute on the ConnectionFactory here:
https://github.com/ibm-messaging/mq-golang-jms20/blob/main/largemessage_test.go#L67

specifically;
```golang

        ...

        // Since the buffer size is configured using the ConnectionFactoy we will
	// create a second connection in order to successfully retrieve the message.
	cf.ReceiveBufferSize = 153600

        context2, ctxErr2 := cf.CreateContext()
        ...
```
(or equivalently if you are initializing the ConnectionFactory from a JSON object or similar)

let me know if that fixes the problem for you.

**Comment by ChipArtem** [comment]
@matrober-uk Thanks you are very helpful!

**Comment by matrober-uk** [comment]
my pleasure, thanks for getting in contact!
