### ISSUE TITLE
 problems starting up in Openshift

### ISSUE THREAD

**Issue by comfysweet** [ibm-messaging/mq-golang-jms20#8]
Hello!
I get an error when I start the application in Openshift: "AMQ6300E: Directory '//.mqm' could not be created: '£'.
panic: {errorCode=2009, reason=MQRC_CONNECTION_BROKEN, linkedErr=MQCONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_CONNECTION_BROKEN [2009]}" 
When I launch it in docker-container or locally, this problem does not occur

**Comment by matrober-uk** [comment]
Hi @comfysweet - welcome!

I think the AMQ6300E error you are seeing is probably because the user under which your container image is running does not have permissions to create that directory due to the OpenShift security constraints (which are more restrictive by default than when you run something in plain docker or locally).

I would suggest that you create that directory as part of your container creation process and ensure that the application user has read/write access to it (e.g. in your Dockerfile), so that it will already be available when your application code executes at runtime.

regards.

**Comment by matrober-uk** [comment]
I finally got around to trying this out for myself, and I've written a template application sample which is now available along with instructions for use at;
    https://github.com/ibm-messaging/mq-golang-jms20/tree/master/openshift-app-sample

As I suspected the above the best approach to addressing the "AMQ6300E: Directory --- could not be created" issue is to add it as part of the container build step, which occurs here in my sample; https://github.com/ibm-messaging/mq-golang-jms20/blob/master/openshift-app-sample/Dockerfile#L29

I'm also planning to publish a blog post that shows the "working" of how I built up that sample.

**Comment by matrober-uk** [comment]
The blog post I mentioned that contains the full working steps for building up an OpenShift application for the MQ client from scratch is now available here;

https://community.ibm.com/community/user/integration/blogs/matt-roberts1/2021/03/12/mq-golangjms-openshift
